# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
 branches:
   include:
     - main

pool:
  vmImage: 'ubuntu-latest'


resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build mavan
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: JavaToolInstaller@1
      inputs:
        versionSpec: '17'
    
    - task: Maven@4
      inputs:
        mavenVersionOption: '3.x'
    
    - script: mvn clean install -DskipTests=true
      displayName: 'Maven Clean Install'
      
    - script: mvn package -DskipTests
      displayName: 'Maven Package'
